name: ua-parser-js-run-test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, ppc64le]
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
      - name: Run the test
        run: |
          npm install
          npm run test-ci
